package com.axisbank.kmm.resources

data class StringResources(
    val button: String = "Button",
    val buttonDescription: String = "The Button enables the user to initiate an action or process",
    val arctic: String = "Arctic",
    val component: String = "Component",
    val increase : String = "Increase",
    val decrease : String = "Decrease",
    val setBadgeEmpty : String = "Set Empty",
    val clearBadge : String = "CLEAR BADGE",
    val setBadgeMax : String = "Set 99",
    val errorMessage : String = "Error message",
    val successMessage : String = "Success message",
    val successString : String = "Success",
    val withOutPlaceholder : String = "Without Placeholder",
    val withPlaceholder : String = "With Placeholder",
    val selectedString : String = "Selected",
    val labelString : String = "Label",
    val dropdownString : String = "Dropdown",
    val enabledString : String = "Enabled",
    val disabledString : String = "Disabled",
    val errorString : String = "Error",
    val withOutHelperString : String = "Without Helper",
    val tabsString : String = "Tabs",
    val defaultTabsString : String = "Default Tabs",
    val defaultTabsDisabledString : String = "Default Tabs Disabled" ,
    val containerTabsString : String = "Container Tabs" ,
    val containerTabsDisabledString : String = "Container Tabs Disabled" ,
    val defaultTabsWithAssetsString : String = "Default Tabs With Assets" ,
    val defaultScrollableTabsString : String = "Default Scrollable Tabs" ,
    val defaultScrollableTabsWithAssetsString : String = "Default Scrollable Tabs With Assets" ,
    val defaultScrollableTabsDisabledString : String = "Default Scrollable Tabs Disabled" ,
    val containerTabsWithAssetsString : String = "Container Tabs With Assets" ,
    val containerTabsDisabledWithAssetsString : String = "Container Tabs Disabled With Assets" ,
    val scrollableContainerTabsString : String = "Scrollable Container Tabs" ,
    val scrollableContainerTabsWithAssetsString : String = "Scrollable Container Tabs With Assets" ,
    val disabledScrollableContainerString : String = "Disabled Scrollable Container" ,
    val disabledScrollableContainerTabsWithAssetsString : String = "Disabled Scrollable Container Tabs With Assets" ,
    )
